; Note: lines starting with semicolon are for comments.
; Load plugins for any title.

[default]
/data/GoldHEN/plugins/game_patch.prx

; DRIVECLUB BEGIN

; Europe, Germany
[CUSA00003]
/data/GoldHEN/plugins/afr.prx
/data/GoldHEN/plugins/no_share_watermark.prx

; USA, Brazil, Canada, South America
[CUSA00093]
/data/GoldHEN/plugins/afr.prx
/data/GoldHEN/plugins/no_share_watermark.prx

; China
[CUSA00879]
/data/GoldHEN/plugins/afr.prx
/data/GoldHEN/plugins/no_share_watermark.prx

; Japan
[PCJS50001]
/data/GoldHEN/plugins/afr.prx
/data/GoldHEN/plugins/no_share_watermark.prx

; Japan
[CUSA00064]
/data/GoldHEN/plugins/afr.prx
/data/GoldHEN/plugins/no_share_watermark.prx

; Korea
[PCKS90001]
/data/GoldHEN/plugins/afr.prx
/data/GoldHEN/plugins/no_share_watermark.prx

; Asia
[PCAS00001]
/data/GoldHEN/plugins/afr.prx
/data/GoldHEN/plugins/no_share_watermark.prx

; Asia
[PCAS20004]
/data/GoldHEN/plugins/afr.prx
/data/GoldHEN/plugins/no_share_watermark.prx

; Korea
[PCKS70004]
/data/GoldHEN/plugins/afr.prx
/data/GoldHEN/plugins/no_share_watermark.prx

; Japan
[PCJS73508]
/data/GoldHEN/plugins/afr.prx
/data/GoldHEN/plugins/no_share_watermark.prx

; DRIVECLUB END